#:schema https://tahv.codeberg.page/menuet/menuet.json

[[menu]]
label = "Animation"
icon = "res:menuet.demo:lucide-clapperboard.svg"

[[menu]]
label = "Modeling"
icon = "res:menuet.demo:lucide-box.svg"

[[menu]]
label = "Development"
icon = "res:menuet.demo:lucide-code-xml.svg"

[[menu]]
label = "Rigging"
icon = "res:menuet.demo:lucide-bone.svg"

[[action]]
id = "anim-bake"
label = "Bake Animation"
menu = ["Animation"]
desc = "Bake selected character(s) animation"

[[action]]
id = "anim-fbx-exporter"
label = "FBX Animation Exporter"
menu = ["Animation", "FBX"]
desc = "Open animation exporter Window"
icon = "res:menuet.demo:lucide-file-up.svg"

[[action]]
id = "anim-fbx-importer"
label = "FBX Animation Importer"
menu = ["Animation", "FBX"]
desc = "Open animation importer Window"
icon = "res:menuet.demo:lucide-file-down.svg"

[[action]]
id = "adjustment-blending"
label = "Adjustment Blending"
menu = ["Animation"]
group = "Edit"
desc = "Perform Adjustment Blending on selected character(s)"

[[action]]
id = "tween-machine"
label = "Tween Machine"
menu = ["Animation"]
group = "Edit"
icon = "res:menuet.demo:lucide-align-horizontal-space-around.svg"

[[action]]
id = "rig-ctrl-creator"
label = "Controller Creator"
menu = ["Rigging"]
group = "Controller"
icon = "res:menuet.demo:lucide-box.svg"

[[action]]
id = "rig-ctrl-editor"
label = "Controller Editor"
menu = ["Rigging"]
group = "Controller"
icon = "res:menuet.demo:lucide-box.svg"

[[action]]
id = "rig-joint-tools"
label = "Joint Tools"
menu = ["Rigging"]
icon = "res:menuet.demo:lucide-bone.svg"

[[action]]
id = "rig-skinning-tools"
label = "Skinning Tools"
menu = ["Rigging"]
icon = "res:menuet.demo:lucide-paintbrush.svg"

[[action]]
id = "mesh-mirror"
label = "Mirror Geometry"
menu = ["Modeling"]
icon = "res:menuet.demo:lucide-flip-horizontal-2.svg"

[[action]]
id = "mesh-cleaner"
label = "Mesh Cleaner"
menu = ["Modeling"]
icon = "res:menuet.demo:lucide-brush-cleaning.svg"

[[action]]
id = "mesh-randomizer"
label = "Mesh Randomizer"
menu = ["Modeling"]
icon = "res:menuet.demo:lucide-shuffle.svg"

[[action]]
id = "dev-debugger"
label = "Start Debugger"
menu = ["Development"]
icon = "res:menuet.demo:lucide-bug.svg"

[[action]]
id = "doc-open"
label = "Open Documentation"
cb = "url:https://tahv.codeberg.page/menuet/"
icon = "res:menuet.demo:lucide-info.svg"
