# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - evaluate: >
      CI_PIPELINE_EVENT == "tag"
      && CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH

steps:
  build:
    name: Build Pages
    image: ghcr.io/astral-sh/uv:python3.14-trixie
    commands:
      - uv run --group dev -m zensical build --clean

  deploy:
    name: Deploy Pages
    image: codeberg.org/sugar700/plugin-codeberg-pages-deploy:1
    settings:
      folder: site
      branch: pages
      ssh_key:
        from_secret: ssh_key
