# startup/               # directory must be in 'HOUDINI_PATH'
# ├── python3.11libs/
# │   └── pythonrc.py    # this file
# └── MainMenuCommon.xml # generated by this file
from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING

import hou

from menuet.builders.houdini import HoudiniXmlMainMenuBuilder, InsertBefore
from menuet.demo import demo_model

if TYPE_CHECKING:
    from collections.abc import Callable


def to_string_command_factory(model: str) -> Callable[[str], str]:
    """Generate `to_string_command` argument from a `Model` reference."""

    def inner(action: str) -> str:
        return f"""\
        from importlib.metadata import EntryPoint
        model_loader = EntryPoint(name="", group="", value='{model}').load()
        model = model_loader()
        model.get_action('{action}').cb()
        """

    return inner


# build and write menu xml file
model = demo_model()
builder = HoudiniXmlMainMenuBuilder(
    model,
    root_menu="Demo",
    to_string_command=to_string_command_factory("menuet.demo:demo_model"),
    position=InsertBefore("help_menu"),
)
menu_file = Path("startup/MainMenuCommon.xml")
menu_file.parent.mkdir(parents=True, exist_ok=True)
menu_file.write_text(builder.build())

# add the xml parent directory to 'HOUDINI_MENU_PATH'
existing = hou.getenv("HOUDINI_MENU_PATH")
edited = existing.split(os.pathsep) if existing is not None else ["&"]
edited = [str(menu_file), *edited]
hou.putenv("HOUDINI_MENU_PATH", os.pathsep.join(edited))

# refresh houdini cache so it read the xml
if hou.applicationVersion() >= (21,):
    hou.refreshStartupPathCacheDirectory(str(menu_file.parent))
